### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tail'

### ISSUE THREAD

**Issue by PvrpleBlvck** [krivi95/option-pricing-models#6]
Just a quick question , i get this error when i run the script. I believe yours work. Am new to python. Would you mind helping me out. 

``` streamlit_app.py", line 41, in <module>```
    st.write(data.tail())

Appreciate it thank you.

**Comment by just-krivi** [comment]
Hi,

The repo hasn't been updated in a while, I'm planning to do refactoring and to update it a bit in the following weeks.

I believe that `pandas-datareader` which is used for getting the data for the selected ticker changed its interface. The reason why you saw the error is that it was unable to fetch the prices for the stock you selected. It returned `None` and the exception was raised in streamlit on that line `data.tail()`.

I believe that this PR #7 fixes that (it's merged to the master branch, you can just pull the latest commit), at least it worked for me. Please let me know if that helped.

**Comment by just-krivi** [comment]
You may also see the other project that may be useful - [option pricing via Fourier Transform](https://github.com/mcf-long-short/option-pricing-fourier-transform). The interface is pretty similar to this, the only difference is the pricing models. It's a few months old repository, so there should be newer versions of libs.

**Comment by PvrpleBlvck** [comment]
Alright i will check it out thank you.
